name: ${project.name}
description: ${project.description}
version: ${project.version}-b${buildNumber}
author: ${author}
website: ${project.url}

main: ${mainClass}

permissions:
  commandtimer.*:
    description: Grants all CommandTimer permissions.
    children:
      - commandtimer.bypass
  commandtimer.bypass:
    description: Allows bypassing of all CommandTimer timers.

